version: 1.0.{build}
branches:
  only:
  - xyginext
cache: c:/Tools/vcpkg
build_script:
- cmd: >-
    cd c:/tools/vcpkg

    git pull

    cd c:/projects/xygine

    mkdir build && cd build

    vcpkg install sfml enet

    cmake ../xyginext -DCMAKE_TOOLCHAIN_FILE=C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake

    cmake --build .